name: linux

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install glfw
      run: |
        sudo apt-get update && sudo apt-get -y upgrade
        sudo apt-get install -y libglfw3 libglfw3-dev xf86vmode-dev build-essential git cmake
    - name: make
      run: |
        mkdir build
        cd build
        cmake ..
        make
        make install
