name: Ubuntu Build

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install glfw
      run: sudo apt-get install -y libglfw3 libglfw3-dev
    - name: make
      run: make
